name: db_benchmarks
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.2
  hive: ^2.2.3
  sqflite: ^2.0.0+3
  sembast: ^3.2.0+1
  objectbox: ^2.4.0
  objectbox_flutter_libs: any
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  sqflite_common_ffi: ^2.2.1+1
  sqlite3_flutter_libs: ^0.5.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.0.0
  objectbox_generator: any
  isar_generator: any

flutter:

  uses-material-design: true
